apiVersion: v1
kind: Pod
metadata:
  name: "webserver-pod"
  namespace: default
  labels:
    app: "webserver-pod"
spec:
  containers:
  - name: webserver-pod
    image: "nginx"
    ports:
    - containerPort:  8080
      name:  http
  restartPolicy: Always